In [1]:
import h5py
import numpy as np
import pandas as pd
import json

In [6]:
files = [
    "val_18k.h5",
    "val_700k_strong.h5",
    "val_9k.h5",
    "val_cnn_lstm_sa_mlp.h5",
    "val_cnn_lstm_sa.h5",
    "val_cnn_lstm.h5",
    "val_lstm.h5"
]

In [4]:
scene_file = 'CLEVR_val_scenes.json'
with open(scene_file) as f:
    scenes = json.load(f)
    scenes_info = scenes["info"]
    scenes = scenes["scenes"]
question_file = 'CLEVR_val_questions.json'
with open(question_file) as f:
    questions = json.load(f)
    questions_info = questions["info"]
    questions = questions["questions"]
print("Questions info: ", questions_info)
print("Scenes_info: ", scenes_info)

Questions info:  {'split': 'val', 'license': 'Creative Commons Attribution (CC BY 4.0)', 'version': '1.0', 'date': '2/14/2017'}
Scenes_info:  {'split': 'val', 'license': 'Creative Commons Attribution (CC BY 4.0)', 'version': '1.0', 'date': '2/14/2017'}

In [21]:
df = pd.DataFrame([])

In [22]:
for file in files:
    f = h5py.File(file, "r")
    keys = f.keys()
    print("keys of ", file, ": ", keys)
    column_name = file[4:-3]
    df[column_name + "_correct"] = f["correct"][:].flatten()
    df[column_name + "_preds"] = f["preds"][:].flatten()

keys of  val_18k.h5 :  <KeysViewHDF5 ['correct', 'predicted_programs', 'preds', 'probs', 'scores']>
keys of  val_700k_strong.h5 :  <KeysViewHDF5 ['correct', 'predicted_programs', 'preds', 'probs', 'scores']>
keys of  val_9k.h5 :  <KeysViewHDF5 ['correct', 'predicted_programs', 'preds', 'probs', 'scores']>
keys of  val_cnn_lstm_sa_mlp.h5 :  <KeysViewHDF5 ['correct', 'preds', 'probs', 'scores']>
keys of  val_cnn_lstm_sa.h5 :  <KeysViewHDF5 ['correct', 'preds', 'probs', 'scores']>
keys of  val_cnn_lstm.h5 :  <KeysViewHDF5 ['correct', 'preds', 'probs', 'scores']>
keys of  val_lstm.h5 :  <KeysViewHDF5 ['correct', 'preds', 'probs', 'scores']>

In [23]:
print(questions[0].keys())
print(questions[10]["answer"])

dict_keys(['image_index', 'program', 'question_index', 'image_filename', 'question_family_index', 'split', 'answer', 'question'])
cyan

In [29]:
df["image_index"] = ""
df["question_index"] = ""
df["question_family_index"] = ""
df["answer"] = ""
df["question"] = ""
df["image_filename"] = ""
for i in range(df.shape[0]):
    df.at[i, "image_index"] = questions[i]["image_index"]
    df.at[i, "question_index"] = questions[i]["question_index"]
    df.at[i, "question_family_index"] = questions[i]["question_family_index"]
    df.at[i, "answer"] = questions[i]["answer"]
    df.at[i, "question"] = questions[i]["question"]
    df.at[i, "image_filename"] = questions[i]["image_filename"]

In [30]:
df

,18k_correct,18k_preds,700k_strong_correct,700k_strong_preds,9k_correct,9k_preds,cnn_lstm_sa_mlp_correct,cnn_lstm_sa_mlp_preds,cnn_lstm_sa_correct,cnn_lstm_sa_preds,cnn_lstm_correct,cnn_lstm_preds,lstm_correct,lstm_preds,image_index,question_index,question_family_index,answer,question,image_filename
0,1,24,1,24,1,24,1,24,1,24,1,24,0,31,0,0,39,no,Are there any other things that are the same s...,CLEVR_val_000000.png
1,1,31,1,31,1,31,0,24,0,24,0,24,0,24,0,1,47,yes,Is there a big brown object of the same shape ...,CLEVR_val_000000.png
2,1,23,1,23,1,23,1,23,1,23,1,23,1,23,0,2,87,metal,What is the material of the big purple object?,CLEVR_val_000000.png
3,1,31,1,31,1,31,0,24,1,31,0,24,1,31,0,3,73,yes,There is a small gray block; are there any sph...,CLEVR_val_000000.png
4,1,24,1,24,1,24,1,24,1,24,1,24,1,24,0,4,12,no,Is the purple thing the same shape as the larg...,CLEVR_val_000000.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149986,1,23,1,23,1,23,1,23,1,23,1,23,1,23,14999,149986,56,metal,There is a object that is the same color as th...,CLEVR_val_014999.png
149987,1,27,1,27,1,27,1,27,1,27,1,27,0,23,14999,149987,53,rubber,There is a brown ball that is the same size as...,CLEVR_val_014999.png
149988,1,31,1,31,1,31,1,31,0,24,1,31,1,31,14999,149988,45,yes,Are there any tiny objects that have the same ...,CLEVR_val_014999.png
149989,1,29,1,29,1,29,0,17,1,29,1,29,0,17,14999,149989,35,sphere,There is a small object that is both on the ri...,CLEVR_val_014999.png
149990,1,4,1,4,1,4,1,4,1,4,1,4,0,5,14999,149990,50,0,What number of large cubes have the same mater...,CLEVR_val_014999.png

In [31]:
df.to_csv("val_results.csv", index = False)